version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "melvyndekort"
    reviewers:
      - "melvyndekort"
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "melvyndekort"
    reviewers:
      - "melvyndekort"
